# Proyecto Métodos y Aplicaciones de Analítica ll
Caso de estudio: Improving Lead Generation at Eureka Forbes Using Machine Learning Algorithms




# Parte 1 - Base sin balancear
## Preparación de los datos
Se realizó un preprocesamiento sencillo de los datos en Knime y se procede a importar la base #1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Cargar los paquetes y librerías necesarios 

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_curve, auc, roc_auc_score, classification_report, confusion_matrix, make_scorer


# Cargar los datos desde el archivo CSV en el dataframe llamado df.
df = pd.read_csv("/content/drive/MyDrive/Proyecto_Analitica_2/base_1.csv", sep=",", header = 0)  
df.head()

DemoReqPg_CallClicks_evt_count  air_purifier_page_top  bounces  \
0                               0                      0        0   
1                               0                      0        0   
2                               0                      0        0   
3                               0                      0        1   
4                               0                      0        1   

   checkout_page_top  contactus_top  converted_in_7days  \
0                  0              0                   0   
1                  0              0                   0   
2                  0              0                   0   
3                  0              0                   0   
4                  0              0                   0   

   customer_service_amc_login_top  customer_service_request_login_top  \
0                               0                                   0   
1                               0                                   0   
2                               0                                   0   
3                               0                                   0   
4                               0                                   0   

   demo_page_top  dsls  ...  2019-02-22  2019-02-23  2019-02-24  2019-02-25  \
0              0     0  ...           0           0           0           0   
1              7     6  ...           0           0           0           0   
2              0     1  ...           0           0           0           0   
3              0     0  ...           0           0           0           0   
4              0     0  ...           0           0           0           0   

   2019-02-26  2019-02-27  2019-02-28  2019-03-01  mobile  desktop  
0           0           0           0           0       1        0  
1           0           0           0           0       1        0  
2           0           0           0           0       1        0  
3           0           0           0           0       1        0  
4           0           0           0           0       1        0  

[5 rows x 101 columns]

In [ ]:
# Definición de X y Y
y = df['converted_in_7days']
X = df.drop(columns = 'converted_in_7days')
# Definimos la semilla para el generador de número aleatorios
np.random.seed(77300)

# Dividimos los datos aleatoriamente en 80% para entrenamiento y 20% para prueba 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, stratify=y)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Modelo SVM

In [ ]:
from sklearn import svm
# Desarrollamos un clasificador SVM LINEAL
clfl = svm.SVC(kernel='linear', C=5, random_state=1234) # Linear Kernel

# Entrenamos el modelo usando el dataset de entrenamiento
clfl.fit(X_train, y_train)

#Pronosticamos la respuesta para el dataset de prueba
#En entrenamiento
y_pred_t = clfl.predict(X_train)
#En prueba
y_pred = clfl.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

## Modelo con Red Neuronal

In [ ]:
#librerías y paquetes
import tensorflow as tf
from tensorflow import keras
!pip install -q -U keras-tuner
import numpy as np 
import pandas as pd
import keras_tuner as tk # instalar por cmd
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import SGD
from keras.optimizers import Adam
from keras.utils import to_categorical
from matplotlib import pyplot

model1 = Sequential()
   
model1.add(tf.keras.layers.Dense(units=60, activation="linear",input_dim=100))
model1.add(tf.keras.layers.Dense(units=30, activation="linear"))
model1.add(Dense(1, activation='sigmoid',use_bias=True))

model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss='BinaryCrossentropy',metrics=['accuracy'])
model1.fit(X_train,y_train,epochs=15)
print(model1.summary())

#Pronosticamos la respuesta para el dataset de prueba
#En entrenamiento
y_pred_t = model1.predict(X_train)
#En prueba
y_pred = model1.predict(X_test)

class_threshold = 0.5
y_pred_t = np.where(y_pred_t > class_threshold, 1, 0) # clasificación
y_pred = np.where(y_pred > class_threshold, 1, 0) # clasificación


from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

     |████████████████████████████████| 135 kB 4.0 MB/s 
     |████████████████████████████████| 1.6 MB 19.2 MB/s 
Epoch 1/15
17732/17732 [==============================] - 36s 2ms/step - loss: 0.0298 - accuracy: 0.9951
Epoch 2/15
17732/17732 [==============================] - 35s 2ms/step - loss: 0.0242 - accuracy: 0.9961
Epoch 3/15
17732/17732 [==============================] - 35s 2ms/step - loss: 0.0242 - accuracy: 0.9961
Epoch 4/15
17732/17732 [==============================] - 34s 2ms/step - loss: 0.0241 - accuracy: 0.9961
Epoch 5/15
17732/17732 [==============================] - 35s 2ms/step - loss: 0.0241 - accuracy: 0.9961
Epoch 6/15
17732/17732 [==============================] - 35s 2ms/step - loss: 0.0241 - accuracy: 0.9961
Epoch 7/15
17732/17732 [==============================] - 34s 2ms/step - loss: 0.0241 - accuracy: 0.9961
Epoch 8/15
17732/17732 [==============================] - 37s 2ms/step - loss: 0.0241 - accuracy: 0.9961
Epoch 9/15
17732/17732 [=====================

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    565197
           1       0.00      0.00      0.00      2198

    accuracy                           1.00    567395
   macro avg       0.50      0.50      0.50    567395
weighted avg       0.99      1.00      0.99    567395

[[141300      0]
 [   549      0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    141300
           1       0.00      0.00      0.00       549

    accuracy                           1.00    141849
   macro avg       0.50      0.50      0.50    141849
weighted avg       0.99      1.00      0.99    141849



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Modelo con Random Forest

In [ ]:
# Usando RANDOM FOREST - Modelo 1

from sklearn.ensemble import RandomForestClassifier
RF1 = RandomForestClassifier(n_estimators=30, max_features=50,bootstrap=True, oob_score=False, max_samples=150,random_state=123)
RF1.fit(X_train,y_train)
#Realizando las pruebas
#En entrenamiento
y_pred_t = RF1.predict(X_train)
#En prueba
y_pred = RF1.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[565197      0]
 [  2198      0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    565197
           1       0.00      0.00      0.00      2198

    accuracy                           1.00    567395
   macro avg       0.50      0.50      0.50    567395
weighted avg       0.99      1.00      0.99    567395

[[141300      0]
 [   549      0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    141300
           1       0.00      0.00      0.00       549

    accuracy                           1.00    141849
   macro avg       0.50      0.50      0.50    141849
weighted avg       0.99      1.00      0.99    141849



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Boosting


In [ ]:
# Modelo ADABOOST1

from sklearn.ensemble import AdaBoostClassifier

ada_model1 = AdaBoostClassifier(n_estimators=50, learning_rate=0.1, random_state=0)
ada_model1.fit(X_train, y_train)

#Realizando las pruebas
#En entrenamiento
y_pred_t = ada_model1.predict(X_train)
#En prueba
y_pred = ada_model1.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[565197      0]
 [  2198      0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    565197
           1       0.00      0.00      0.00      2198

    accuracy                           1.00    567395
   macro avg       0.50      0.50      0.50    567395
weighted avg       0.99      1.00      0.99    567395

[[141300      0]
 [   549      0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    141300
           1       0.00      0.00      0.00       549

    accuracy                           1.00    141849
   macro avg       0.50      0.50      0.50    141849
weighted avg       0.99      1.00      0.99    141849



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Parte 2 - Balanceo y redimensionamiento de los datos
## Preparación de los datos
Se realizó un preprocesamiento sencillo de los datos en Knime y se procede a importar la base #2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Cargar los paquetes y librerías necesarios 

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_curve, auc, roc_auc_score, classification_report, confusion_matrix, make_scorer


# Cargar los datos desde el archivo CSV en el dataframe llamado df.
df = pd.read_csv("/content/drive/MyDrive/Proyecto_Analitica_2/base_2.csv", sep=",", header = 0)  
df.head()

converted_in_7days  PCA dimension 0  PCA dimension 1  PCA dimension 2  \
0                 1.0     -1626.396862       -85.483097      -388.754437   
1                 1.0         0.613299       160.911866       -53.362804   
2                 1.0       360.846844       -56.266181        -0.027552   
3                 0.0       307.996026       -24.413788        -7.845746   
4                 0.0       363.248183       -57.707466         0.316363   

   PCA dimension 3  PCA dimension 4  PCA dimension 5  PCA dimension 6  \
0        96.187520        17.936155         5.748191        -0.970148   
1        19.112575        -4.964730         2.022854         0.565770   
2         5.614153         0.912177         0.876995         1.599921   
3         7.613197         0.069570         1.032906         1.488752   
4         5.552635         0.981458         0.853730         1.634890   

   PCA dimension 7  PCA dimension 8  PCA dimension 9  
0        -5.536345        -3.880514        -1.836244  
1        -1.288285        -1.390864         0.169838  
2        -0.502785        -0.655040         0.337473  
3        -0.577260        -0.770256         0.321233  
4        -0.475582        -0.637670         0.364772

In [ ]:
# Definición de X y Y
y = df['converted_in_7days']
X = df.drop(columns = 'converted_in_7days')
# Definimos la semilla para el generador de número aleatorios
np.random.seed(77300)

# Dividimos los datos aleatoriamente en 80% para entrenamiento y 20% para prueba 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, stratify=y)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Modelo SVM

In [ ]:
from sklearn import svm
# Desarrollamos un clasificador SVM LINEAL
clfl = svm.SVC(kernel='linear', C=5, random_state=1234) # Linear Kernel

# Entrenamos el modelo usando el dataset de entrenamiento
clfl.fit(X_train, y_train)

#Pronosticamos la respuesta para el dataset de prueba
#En entrenamiento
y_pred_t = clfl.predict(X_train)
#En prueba
y_pred = clfl.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2075  134]
 [1966  231]]
              precision    recall  f1-score   support

         0.0       0.51      0.94      0.66      2209
         1.0       0.63      0.11      0.18      2197

    accuracy                           0.52      4406
   macro avg       0.57      0.52      0.42      4406
weighted avg       0.57      0.52      0.42      4406

[[510  42]
 [491  59]]
              precision    recall  f1-score   support

         0.0       0.51      0.92      0.66       552
         1.0       0.58      0.11      0.18       550

    accuracy                           0.52      1102
   macro avg       0.55      0.52      0.42      1102
weighted avg       0.55      0.52      0.42      1102



## Modelo con Red Neuronal

In [ ]:
#librerías y paquetes
import tensorflow as tf
from tensorflow import keras
!pip install -q -U keras-tuner
import numpy as np 
import pandas as pd
import keras_tuner as tk # instalar por cmd
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import SGD
from keras.optimizers import Adam
from keras.utils import to_categorical
from matplotlib import pyplot

In [ ]:
# Función para probar hiperparámetros

def model_builder(hp):
    
  hp_activation = hp.Choice('activation', values=['relu', 'tanh','linear','sigmoid'])
  hp_layer_1 = hp.Int('layer_1', min_value=1, max_value=100, step=5)
  hp_layer_2 = hp.Int('layer_2', min_value=1, max_value=100, step=5)
  hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])
 
  model = Sequential()
  model.add(tf.keras.layers.Dense(units=hp_layer_1, activation=hp_activation,input_dim=10))
  model.add(tf.keras.layers.Dense(units=hp_layer_2, activation=hp_activation))
  model.add(Dense(1, activation='sigmoid',use_bias=True))

  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),loss='MeanSquaredError',metrics=['accuracy'])
  
  return model


# Algoritmo Hyperband

tuner = tk.Hyperband(model_builder,
                     objective='val_accuracy',
                     max_epochs=100,
                     factor=5,directory='/content/drive/MyDrive/Proyecto_Analitica_2/RNCLASS-HP8',
                     project_name='RNCLASS-HP8')

# crieterio de parada anticipada
stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
# Búsqueda
tuner.search(X_train, y_train, epochs=50, validation_data=(X_test, y_test), callbacks=[stop_early],verbose=True)
best_model = tuner.get_best_models()[0]
#Resúmen
tuner.search_space_summary()
# Resúmen mejores parámetros
tuner.results_summary()



Trial 59 Complete [00h 00m 30s]
val_accuracy: 0.5916515588760376

Best val_accuracy So Far: 0.6043556928634644
Total elapsed time: 00h 06m 20s


Search space summary
Default search space size: 4
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'linear', 'sigmoid'], 'ordered': False}
layer_1 (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 100, 'step': 5, 'sampling': None}
layer_2 (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 100, 'step': 5, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}
Results summary
Results in /content/drive/MyDrive/Proyecto_Analitica_2/RNCLASS-HP8/RNCLASS-HP8
Showing 10 best trials
Trial summary
Hyperparameters:
activation: linear
layer_1: 61
layer_2: 31
learning_rate: 0.0001
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.6043556928634644
Trial summary
Hyperparameters:
activation: relu
layer_1: 51
layer_2: 71
learning_rate: 0.001
tuner/epochs: 100
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 0.59

In [ ]:
# Construcción del MODELO FINAL

"""
activation: linear
layer_1: 61
layer_2: 31
learning_rate: 0.0001
"""
model1 = Sequential()
   
model1.add(tf.keras.layers.Dense(units=60, activation="linear",input_dim=10))
model1.add(tf.keras.layers.Dense(units=30, activation="linear"))
model1.add(Dense(1, activation='sigmoid',use_bias=True))

model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss='BinaryCrossentropy',metrics=['accuracy'])
model1.fit(X_train,y_train,epochs=200)
print(model1.summary())

#Pronosticamos la respuesta para el dataset de prueba
#En entrenamiento
y_pred_t = model1.predict(X_train)
#En prueba
y_pred = model1.predict(X_test)

class_threshold = 0.5
y_pred_t = np.where(y_pred_t > class_threshold, 1, 0) # clasificación
y_pred = np.where(y_pred > class_threshold, 1, 0) # clasificación


from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



Epoch 1/200
138/138 [==============================] - 1s 2ms/step - loss: 0.6931 - accuracy: 0.5134
Epoch 2/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.5161
Epoch 3/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6928 - accuracy: 0.5163
Epoch 4/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6926 - accuracy: 0.5150
Epoch 5/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.5138
Epoch 6/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6925 - accuracy: 0.5123
Epoch 7/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6923 - accuracy: 0.5082
Epoch 8/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6921 - accuracy: 0.5331
Epoch 9/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.5263
Epoch 10/200
138/138 [==============================] - 0s 2ms/step - loss: 0.6918 - accura

## Modelo con Random Forest

In [ ]:
# Usando RANDOM FOREST - Modelo 1

from sklearn.ensemble import RandomForestClassifier
RF1 = RandomForestClassifier(n_estimators=30, max_features=10,bootstrap=True, oob_score=False, max_samples=500,random_state=123)
RF1.fit(X_train,y_train)
#Realizando las pruebas
#En entrenamiento
y_pred_t = RF1.predict(X_train)
#En prueba
y_pred = RF1.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[1590  619]
 [ 726 1471]]
              precision    recall  f1-score   support

         0.0       0.69      0.72      0.70      2209
         1.0       0.70      0.67      0.69      2197

    accuracy                           0.69      4406
   macro avg       0.70      0.69      0.69      4406
weighted avg       0.70      0.69      0.69      4406

[[335 217]
 [266 284]]
              precision    recall  f1-score   support

         0.0       0.56      0.61      0.58       552
         1.0       0.57      0.52      0.54       550

    accuracy                           0.56      1102
   macro avg       0.56      0.56      0.56      1102
weighted avg       0.56      0.56      0.56      1102



## Boosting


In [ ]:
# Modelo ADABOOST1

from sklearn.ensemble import AdaBoostClassifier

ada_model1 = AdaBoostClassifier(n_estimators=200, learning_rate=0.1, random_state=0)
ada_model1.fit(X_train, y_train)

#Realizando las pruebas
#En entrenamiento
y_pred_t = ada_model1.predict(X_train)
#En prueba
y_pred = ada_model1.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train,y_pred_t))
print(classification_report(y_train,y_pred_t))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1380  829]
 [ 825 1372]]
              precision    recall  f1-score   support

         0.0       0.63      0.62      0.63      2209
         1.0       0.62      0.62      0.62      2197

    accuracy                           0.62      4406
   macro avg       0.62      0.62      0.62      4406
weighted avg       0.62      0.62      0.62      4406

[[319 233]
 [226 324]]
              precision    recall  f1-score   support

         0.0       0.59      0.58      0.58       552
         1.0       0.58      0.59      0.59       550

    accuracy                           0.58      1102
   macro avg       0.58      0.58      0.58      1102
weighted avg       0.58      0.58      0.58      1102

